[package]
name = "core-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "core"
path = "src/main.rs"

[dependencies]
clap.workspace = true
core-config = { path = "../core-config", version = "0.1.0" }
core-contracts = { path = "../core-contracts", version = "0.1.0" }
core-runtime = { path = "../core-runtime", version = "0.1.0" }
serde_json.workspace = true
tokio.workspace = true
