[package]
name = "core-registry"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
core-contracts = { path = "../core-contracts", version = "0.1.0" }
core-identity = { path = "../core-identity", version = "0.1.0" }
serde.workspace = true
thiserror.workspace = true
