[package]
name = "core-config"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
core-contracts = { path = "../core-contracts" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
